export const notifs = [
  {
    id: 1,
    name: "Opeyemi A",
    activity: "Just joined Your Group",
    club: "Positivity Lovers Club",
    dayAndTime: "Today at 9:42 AM",
    isRead: false,
  },
  {
    id: 2,
    name: "Opeyemi A",
    activity: "Just joined Your Group",
    club: "Positivity Lovers Club",
    dayAndTime: "Today at 9:42 AM",
    isRead: false,
  },
  {
    id: 3,
    name: "Opeyemi A",
    activity: "Just joined Your Group",
    club: "Positivity Lovers Club",
    dayAndTime: "Today at 9:42 AM",
    isRead: false,
  },
  {
    id: 4,
    name: "Opeyemi A",
    activity: "Just joined Your Group",
    club: "Positivity Lovers Club",
    dayAndTime: "Today at 9:42 AM",
    isRead: false,
  },
  {
    id: 5,
    name: "Opeyemi A",
    activity: "Just joined Your Group",
    club: "Positivity Lovers Club",
    dayAndTime: "Today at 9:42 AM",
    isRead: true,
  },
  {
    id: 6,
    name: "Opeyemi A",
    activity: "Just joined Your Group",
    club: "Positivity Lovers Club",
    dayAndTime: "Today at 9:42 AM",
    isRead: true,
  },
  {
    id: 7,
    name: "Opeyemi A",
    activity: "Just joined Your Group",
    club: "Positivity Lovers Club",
    dayAndTime: "Today at 9:42 AM",
    isRead: true,
  },
  {
    id: 8,
    name: "Opeyemi A",
    activity: "Just joined Your Group",
    club: "Positivity Lovers Club",
    dayAndTime: "Today at 9:42 AM",
    isRead: true,
  },
  {
    id: 9,
    name: "Opeyemi A",
    activity: "Just joined Your Group",
    club: "Positivity Lovers Club",
    dayAndTime: "Today at 9:42 AM",
    isRead: true,
  },
];