import { HiOutlineDotsVertical } from "react-icons/hi";
import { HiOutlineLocationMarker } from "react-icons/hi";
import attendee1 from "../../../../../public/attendee1.png";
import attendee2 from "../../../../../public/attendee2.png";
export const cardData = [
  {
    date: "SAT, JULY 29, 2023, 4:00PM",
    menuIcon: <HiOutlineDotsVertical />,
    title: "Basketball Hangout",
    locationIcon: <HiOutlineLocationMarker />,
    location: "Leeds, UK",
    description:
      "This is a Basketball group and a group for basketball lovers. We usually meet up at the London Basketball field, near Jameson Park, every Saturday.",
    tag: "Public",
    btn: "View details",
    members: [
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
    ],
  },
  {
    date: "SAT, JULY 29, 2023, 4:00PM",
    menuIcon: <HiOutlineDotsVertical />,
    title: "Basketball Hangout",
    locationIcon: <HiOutlineLocationMarker />,
    location: "Leeds, UK",
    description:
      "This is a Basketball group and a group for basketball lovers. We usually meet up at the London Basketball field, near Jameson Park, every Saturday.",
    tag: "Private",
    btn: "View details",
    members: [
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
    ],
  },
  {
    date: "SAT, JULY 29, 2023, 4:00PM",
    menuIcon: <HiOutlineDotsVertical />,
    title: "Basketball Hangout",
    locationIcon: <HiOutlineLocationMarker />,
    location: "Leeds, UK",
    description:
      "This is a Basketball group and a group for basketball lovers. We usually meet up at the London Basketball field, near Jameson Park, every Saturday.",
    tag: "Private",
    btn: "View details",
    members: [
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
    ],
  },
  {
    date: "SAT, JULY 29, 2023, 4:00PM",
    menuIcon: <HiOutlineDotsVertical />,
    title: "Basketball Hangout",
    locationIcon: <HiOutlineLocationMarker />,
    location: "Leeds, UK",
    description:
      "This is a Basketball group and a group for basketball lovers. We usually meet up at the London Basketball field, near Jameson Park, every Saturday.",
    tag: "Public",
    btn: "View details",
    members: [
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
    ],
  },
  {
    date: "SAT, JULY 29, 2023, 4:00PM",
    menuIcon: <HiOutlineDotsVertical />,
    title: "Basketball Hangout",
    locationIcon: <HiOutlineLocationMarker />,
    location: "Leeds, UK",
    description:
      "This is a Basketball group and a group for basketball lovers. We usually meet up at the London Basketball field, near Jameson Park, every Saturday.",
    tag: "Public",
    btn: "View details",
    members: [
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
    ],
  },
  {
    date: "SAT, JULY 29, 2023, 4:00PM",
    menuIcon: <HiOutlineDotsVertical />,
    title: "Basketball Hangout",
    locationIcon: <HiOutlineLocationMarker />,
    location: "Leeds, UK",
    description:
      "This is a Basketball group and a group for basketball lovers. We usually meet up at the London Basketball field, near Jameson Park, every Saturday.",
    tag: "Private",
    btn: "View details",
    members: [
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
    ],
  },
  {
    date: "SAT, JULY 29, 2023, 4:00PM",
    menuIcon: <HiOutlineDotsVertical />,
    title: "Basketball Hangout",
    locationIcon: <HiOutlineLocationMarker />,
    location: "Leeds, UK",
    description:
      "This is a Basketball group and a group for basketball lovers. We usually meet up at the London Basketball field, near Jameson Park, every Saturday.",
    tag: "Private",
    btn: "View details",
    members: [
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
    ],
  },
  {
    date: "SAT, JULY 29, 2023, 4:00PM",
    menuIcon: <HiOutlineDotsVertical />,
    title: "Basketball Hangout",
    locationIcon: <HiOutlineLocationMarker />,
    location: "Leeds, UK",
    description:
      "This is a Basketball group and a group for basketball lovers. We usually meet up at the London Basketball field, near Jameson Park, every Saturday.",
    tag: "Public",
    btn: "View details",
    members: [
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
      { src: attendee1, alt: "Member" },
      { src: attendee2, alt: "Member" },
    ],
  },
];
